# plugins_lazy.toml は特定の拡張子を開いた時にだけ読み込む設定を記述します。
#
# 概要
#   plugins.tomlに記述するべき設定は特定の拡張子のファイルを開くときだけ読み込ん
#   で欲しい設定です。

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = 'source ~/.vim/rc/plugins/emmet-vim.vim'
on_ft = ['html', 'php', 'javascript', 'typescript']

[[plugins]]
repo = 'PProvost/vim-ps1'
on_ft = ['ps1']

[[plugins]]
repo = 'fatih/vim-go'
hook_add = 'source ~/.vim/rc/plugins/vim-go.vim'
on_ft = ['go']

[[plugins]]
repo = 'keith/swift.vim'
on_ft = ['swift']

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['plantuml']

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
hook_add = 'source ~/.vim/rc/plugins/vim-markdown.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_add = 'source ~/.vim/rc/plugins/vim-table-mode.vim'
on_ft = ['text', 'markdown']

[[plugins]]
repo = 'jpalardy/vim-slime'
hook_add = 'source ~/.vim/rc/plugins/vim-slime.vim'
on_ft = ['elisp', 'clojure']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html', 'css']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['html', 'javascript']

[[plugins]]
repo = 'tpope/vim-surround'
on_ft = ['html', 'javascript']
