[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = 'source ~/.vim/rc/plugins/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'h1mesuke/vim-alignta'
hook_add = 'source ~/.vim/rc/plugins/vim-alignta.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = 'source ~/.vim/rc/plugins/memolist.vim'

[[plugins]]
repo = 'twitvim/twitvim'
hook_add = 'source ~/.vim/rc/plugins/twitvim.vim'

