# plugins.toml は常時読み込むプラグインの設定を記述します。
#
# 概要
#   plugins.tomlに記述するべき設定は特定の拡張子のファイルを開くときだけ読み込ん
#   で欲しい設定ではなく、常に読み込むひつようのあるプラグインの設定です。
#
#   拡張子ごとに遅延読み込みする設定はplugins_lazy.tomlに記述します。

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = 'source ~/.vim/rc/plugins/unite.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = 'source ~/.vim/rc/plugins/neocomplete.vim'
on_i = 1

# vimfiler系 unite, deniteに依存しないファイラ
[[plugins]]
repo = 'cocopon/vaffle.vim'
hook_add = 'source ~/.vim/rc/plugins/vaffle.vim'

# Python3の導入がめんどくさそうだったんで保留
#[[plugins]]
#repo = 'Shougo/denite.nvim'
#hook_add = 'source ~/.vim/rc/plugins/denite.vim'
#
#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#hook_add = 'source ~/.vim/rc/plugins/deoplete.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

# Git
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'source ~/.vim/rc/plugins/vim-fugitive.vim'

# Gitの差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/.vim/rc/plugins/vim-gitgutter.vim'

# deopleteにpythonの自動補間を提供
#[[plugins]]
#repo = 'zchee/deoplete-jedi'

# linterによる構文チェック
#[[plugins]]
#repo = 'w0rp/ale'
#hook_add = 'source ~/.vim/rc/plugins/ale.vim'

# 2018/02/24 Win10で動作せずにつきコメントアウト
## ctags, gtags
#[[plugins]]
#repo = 'jsfaint/gen_tags.vim'
#hook_add = 'source ~/.vim/rc/plugins/gen_tags.vim'

# 桁揃え
[[plugins]]
repo = 'h1mesuke/vim-alignta'
hook_add = 'source ~/.vim/rc/plugins/vim-alignta.vim'

# メモ
[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = 'source ~/.vim/rc/plugins/memolist.vim'

# Twitter
[[plugins]]
repo = 'twitvim/twitvim'
hook_add = 'source ~/.vim/rc/plugins/twitvim.vim'

# Bookmark
[[plugins]]
repo = 'MattesGroeger/vim-bookmarks'
hook_add = 'source ~/.vim/rc/plugins/vim-bookmarks.vim'

