# 自分以外のプラグイン {{{

[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = 'source ~/.vim/rc/plugins/neocomplete.vim'
on_i = 1

# unite.vimと一緒に起動するプラグイン {{{

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_add = 'source ~/.vim/rc/plugins/vimfiler.vim'
on_source = ['unite.vim']

# }}}
# 特定ファイルタイプのためのプラグイン {{{

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = 'source ~/.vim/rc/plugins/emmet-vim.vim'
on_ft = ['html', 'php', 'javascript', 'typescript']

[[plugins]]
repo = 'PProvost/vim-ps1'
on_ft = ['powershell']

[[plugins]]
repo = 'fatih/vim-go'
hook_add = 'source ~/.vim/rc/plugins/vim-go.vim'
on_ft = ['go']

[[plugins]]
repo = 'keith/swift.vim'
on_ft = ['swift']

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['plantuml']

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
hook_add = 'source ~/.vim/rc/plugins/vim-markdown.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# }}}

# }}}
# 自分のプラグイン {{{

[[plugins]]
repo = 'jiro4989/daylog.vim'
on_ft = ['text', 'markdown']

[[plugins]]
repo = 'jiro4989/todo.txt-vim'
on_ft = ['text']

# }}}

