[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''source expand('<sfile>:p:h')/plugin.d/denite.nvim.vim'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''source expand('<sfile>:p:h')/plugin.d/deoplete.nvim.vim'''
on_i = 1

# filerプラグイン
[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''source expand('<sfile>:p:h')/plugin.d/defx.nvim.vim'''

[[plugins]]
repo = 'Shougo/neomru.vim'

# Git
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''source expand('<sfile>:p:h')/plugin.d/vim-fugitive.vim'''

# Gitの差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''source expand('<sfile>:p:h')/plugin.d/vim-gitgutter.vim'''

# 桁揃え
[[plugins]]
repo = 'h1mesuke/vim-alignta'
hook_add = '''source expand('<sfile>:p:h')/plugin.d/vim-alignta.vim'''

[[plugins]]
repo = 'tpope/vim-surround'

# 括弧閉じ
[[plugins]]
repo = 'cohama/lexima.vim'

# comment out
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''source expand('<sfile>:h')/plugin.d/caw.vim'''

# fold title
[[plugins]]
repo = 'LeafCage/foldCC'

# yank highlight
repo = 'machakann/vim-highlightedyank'

